---
abstract: 'More complex methods for accessing data collected by a Neurio sensor module.'
author:
  - 'Kedar Warriner'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-NeurioTools
no_index:
  directory:
    - t
    - inc
requires:
  DateTime::Format::ISO8601: 0.08
version: 0.03
